services:
    postgresql:
        image: postgres:16
        environment:
            POSTGRES_DB: 'pgsql_db'
            POSTGRES_USER: 'pgsql_user'
            POSTGRES_PASSWORD: 'pgsql_pass'
            PGDATA: '/var/lib/postgresql/data/pgdata'
        volumes:
            - ./storage/postgresql/data:/var/lib/postgresql/data
            - ./docker/postgresql/database/init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
            - ./docker/postgresql/scripts/healthcheck.sh:/usr/local/bin/healthcheck.sh
            - ./logs/postgresql:/var/log/postgresql
        ports:
            - 5432:5432
        healthcheck:
            test: ["CMD-SHELL", "chmod +x docker/postgresql/healthcheck/healthcheck.sh && /usr/local/bin/healthcheck.sh"]
            interval: 1s
            timeout: 5s
            retries: 10

    adminer:
        image: adminer
        ports:
            - 8080:8080
        depends_on:
            - postgresql

    php:
        build:
            context: ./docker/php
            dockerfile: ./dockerfile
        volumes:
            - ./docker/php/config/php.ini:/usr/local/etc/php/conf.d/app-php.ini
            - ./logs/php:/var/log/php
            - ./app:/var/www/html
        depends_on:
            - postgresql

    nginx:
        image: nginx:alpine
        volumes:
            - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
            - ./logs/nginx:/var/log/nginx
            - ./app:/var/www/html
        ports:
            - 80:80
        depends_on:
            - php
            - postgresql
